site_name: My Docs
site_description: Reposit√≥rio da disciplina de MDS
repo_url: https://github.com/RcleydsonR/rafa-robs.git

theme:
    name: readthedocs

plugins:
    - search

nav:
    - Home: "index.md"
